#
# board/renesas/salvator-x/Makefile
#
# Copyright (C) 2015 Renesas Electronics Corporation
#
# SPDX-License-Identifier: GPL-2.0+
#

obj-y	:= rz-cmn.o
obj-$(CONFIG_RCAR_GEN3) += ../rcar-common/common.o
