#
# board/renesas/sparrowhawk/Makefile
#
# Copyright (C) 2025 Marek Vasut <marek.vasut+renesas@mailbox.org>
#
# SPDX-License-Identifier: GPL-2.0+
#

obj-$(CONFIG_XPL_BUILD) += spl_sparrow.o
obj-y	+= sparrowhawk.o
